services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=2003
      - DB_NAME=ClinicManagementNew
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - ./app:/app/app