services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:2003@host.docker.internal:3306/ClinicManagement
      - SECRET_KEY=your-secret-key
    volumes:
      - ./app:/app/app